# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.api.auth_api import AuthApi  # noqa: E501
from test import api_client, users


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = AuthApi(api_client)

    def tearDown(self):
        pass

    def test_auth_controller_login(self):
        """Test case for auth_controller_login

        """
        login_dto = self.api.auth_controller_login(users['ingestor'])
        assert str(login_dto.access_token)

    def test_auth_controller_logout(self):
        """Test case for auth_controller_logout

        It logs the current user out.  # noqa: E501
        """
        login_dto = self.api.auth_controller_login(users['ingestor'])
        self.api.api_client.configuration.access_token = login_dto.access_token
        self.api.auth_controller_logout()

    def test_auth_controller_whoami(self):
        """Test case for auth_controller_whoami

        """
        login_dto = self.api.auth_controller_login(users['ingestor'])
        self.api.api_client.configuration.access_token = login_dto.access_token
        self.api.auth_controller_whoami()


if __name__ == '__main__':
    unittest.main()
