# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import unittest

from scicat_openapi_client.models.update_instrument_dto import \
    UpdateInstrumentDto  # noqa: E501


def make_instance(include_optional):
    """Test UpdateInstrumentDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return UpdateInstrumentDto(
            unique_name=str(random.randint(0, 99999)),
            name='instrument',
            custom_metadata={}
        )
    else:
        return UpdateInstrumentDto()


class TestUpdateInstrumentDto(unittest.TestCase):
    """UpdateInstrumentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredUpdateInstrumentDto(self):
        """Test UpdateInstrumentDto"""
        make_instance(include_optional=False)

    def testOptionalUpdateInstrumentDto(self):
        """Test UpdateInstrumentDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
