# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

import scicat_openapi_client
from scicat_openapi_client.api.default_api import DefaultApi  # noqa: E501
from test import api_client


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = scicat_openapi_client.api.default_api.DefaultApi(
            api_client)  # noqa: E501

    def tearDown(self):
        pass

    def test_health_controller_check(self):
        """Test case for health_controller_check

        """
        self.api.health_controller_check()


if __name__ == '__main__':
    unittest.main()
