# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models. \
    health_controller_check200_response_info_value import \
    (
    HealthControllerCheck200ResponseInfoValue)  # noqa: E501


def make_instance(include_optional):
    """Test HealthControllerCheck200ResponseInfoValue
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return HealthControllerCheck200ResponseInfoValue(
            status=''
        )
    else:
        return HealthControllerCheck200ResponseInfoValue()


class TestHealthControllerCheck200ResponseInfoValue(unittest.TestCase):
    """HealthControllerCheck200ResponseInfoValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredHealthControllerCheck200ResponseInfoValue(self):
        """Test HealthControllerCheck200ResponseInfoValue"""
        make_instance(include_optional=False)

    def testOptionalHealthControllerCheck200ResponseInfoValue(self):
        """Test HealthControllerCheck200ResponseInfoValue"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
