# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.update_user_settings_dto import \
    UpdateUserSettingsDto  # noqa: E501


def make_instance(include_optional):
    """Test UpdateUserSettingsDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return UpdateUserSettingsDto(
            user_id='',
            columns=[
                ''
            ],
            dataset_count=1.337,
            job_count=1.337
        )
    else:
        return UpdateUserSettingsDto()


class TestUpdateUserSettingsDto(unittest.TestCase):
    """UpdateUserSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredUpdateUserSettingsDto(self):
        """Test UpdateUserSettingsDto"""
        make_instance(include_optional=False)

    def testOptionalUpdateUserSettingsDto(self):
        """Test UpdateUserSettingsDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
