# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client import ReturnedAuthLoginDtoUser
from scicat_openapi_client.models.returned_auth_login_dto import \
    ReturnedAuthLoginDto  # noqa: E501


def make_instance(include_optional):
    """Test ReturnedAuthLoginDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return ReturnedAuthLoginDto(
            access_token='',
            id='',
            expires_in=1.337,
            ttl=1.337,
            created='',
            user_id='',
            user=ReturnedAuthLoginDtoUser(
                id='',
                username='',
                email='',
                auth_strategy='')
        )
    else:
        return ReturnedAuthLoginDto(
            access_token='',
            id='',
            expires_in=1.337,
            ttl=1.337,
            created='',
            user_id='',
            user=ReturnedAuthLoginDtoUser(
                id='',
                username='',
                email='',
                auth_strategy=''),
        )


class TestReturnedAuthLoginDto(unittest.TestCase):
    """ReturnedAuthLoginDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredReturnedAuthLoginDto(self):
        """Test ReturnedAuthLoginDto"""
        make_instance(include_optional=False)

    def testOptionalReturnedAuthLoginDto(self):
        """Test ReturnedAuthLoginDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
