# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import datetime
import unittest

import scicat_openapi_client
from scicat_openapi_client.models.proposal_class import \
    ProposalClass  # noqa: E501


def make_instance(include_optional):
    """Test ProposalClass
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return ProposalClass(
            created_by='',
            updated_by='',
            created_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            owner_group='',
            access_groups=[
                ''
            ],
            instrument_group='',
            is_published=True,
            proposal_id='',
            pi_email='',
            pi_firstname='',
            pi_lastname='',
            email='',
            firstname='',
            lastname='',
            title='',
            abstract='',
            start_time=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            end_time=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            measurement_period_list=[
                scicat_openapi_client.models.measurement_period_class
                .MeasurementPeriodClass(
                    created_by='',
                    updated_by='',
                    created_at=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    updated_at=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    instrument='',
                    start=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    end=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    comment='', )
            ]
        )
    else:
        return ProposalClass(
            created_by='',
            updated_by='',
            created_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            owner_group='',
            access_groups=[
                ''
            ],
            is_published=True,
            proposal_id='',
            email='',
            title='',
        )


class TestProposalClass(unittest.TestCase):
    """ProposalClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredProposalClass(self):
        """Test ProposalClass"""
        make_instance(include_optional=False)

    def testOptionalProposalClass(self):
        """Test ProposalClass"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
