# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.api.admin_api import AdminApi  # noqa: E501
from test import api_client, login, logout


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = AdminApi(api_client)
        login(cls.api, 'ingestor')

    @classmethod
    def tearDownClass(cls):
        logout(cls.api)

    def test_admin_controller_get_config(self):
        """Test case for admin_controller_get_config

        """
        response = self.api.admin_controller_get_config()
        assert response['accessTokenPrefix'] == 'Bearer '

    def test_admin_controller_get_theme(self):
        """Test case for admin_controller_get_theme

        """
        response = self.api.admin_controller_get_theme()
        assert response['name']


if __name__ == '__main__':
    unittest.main()
