# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import time
import unittest

from scicat_openapi_client.models.create_sample_dto import \
    CreateSampleDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateSampleDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return CreateSampleDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            sample_id=str(random.randint(0, 99999)),
            owner='ingestor',
            description='Description',
            sample_characteristics=None,
            is_published=True
        )
    else:
        return CreateSampleDto(
            owner_group='ingestor',
        )


class TestCreateSampleDto(unittest.TestCase):
    """CreateSampleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateSampleDto(self):
        """Test CreateSampleDto"""
        make_instance(include_optional=False)

    def testOptionalCreateSampleDto(self):
        """Test CreateSampleDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
