# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

import scicat_openapi_client
from scicat_openapi_client.api.user_identities_api import \
    UserIdentitiesApi  # noqa: E501
from test import api_client, login, logout


class TestUserIdentitiesApi(unittest.TestCase):
    """UserIdentitiesApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = (scicat_openapi_client.api.user_identities_api
        .UserIdentitiesApi(
            api_client))
        login(cls.api, 'admin')

    @classmethod
    def tearDownClass(cls):
        logout(cls.api)

    def test_user_identities_controller_find_one(self):
        """Test case for user_identities_controller_find_one

        """
        self.api.user_identities_controller_find_one('{}')

    def test_user_identities_controller_is_valid_email(self):
        """Test case for user_identities_controller_is_valid_email

        """
        self.api.user_identities_controller_is_valid_email('{}')


if __name__ == '__main__':
    unittest.main()
