# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import unittest

from scicat_openapi_client.models.update_sample_dto import \
    UpdateSampleDto  # noqa: E501


def make_instance(include_optional):
    """Test UpdateSampleDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return UpdateSampleDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            sample_id=str(random.randint(0, 99999)),
            owner='ingestor',
            description='Description',
            sample_characteristics={},
            is_published=True
        )
    else:
        return UpdateSampleDto()


class TestUpdateSampleDto(unittest.TestCase):
    """UpdateSampleDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredUpdateSampleDto(self):
        """Test UpdateSampleDto"""
        make_instance(include_optional=False)

    def testOptionalUpdateSampleDto(self):
        """Test UpdateSampleDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
