# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.health_controller_check200_response import \
    HealthControllerCheck200Response  # noqa: E501


def make_instance(include_optional):
    """Test HealthControllerCheck200Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return HealthControllerCheck200Response(
            status='ok',
            info={"database": {"status": "up"}},
            error={},
            details={"database": {"status": "up"}}
        )
    else:
        return HealthControllerCheck200Response()


class TestHealthControllerCheck200Response(unittest.TestCase):
    """HealthControllerCheck200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredHealthControllerCheck200Response(self):
        """Test HealthControllerCheck200Response"""
        make_instance(include_optional=False)

    def testOptionalHealthControllerCheck200Response(self):
        """Test HealthControllerCheck200Response"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
