# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import time
import unittest

from scicat_openapi_client.models.create_attachment_dto import \
    CreateAttachmentDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateAttachmentDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return CreateAttachmentDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            id=str(random.randint(0, 99999)),
            thumbnail='Thumbnail',
            caption='Caption',
            dataset_id=str(random.randint(0, 99999)),
            proposal_id=str(random.randint(0, 99999)),
            sample_id=str(random.randint(0, 99999))
        )
    else:
        return CreateAttachmentDto(
            owner_group='ingestor',
            caption='Caption',
        )


class TestCreateAttachmentDto(unittest.TestCase):
    """CreateAttachmentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateAttachmentDto(self):
        """Test CreateAttachmentDto"""
        make_instance(include_optional=False)

    def testCreateAttachmentDto(self):
        """Test CreateAttachmentDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
