# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import time
import unittest

from scicat_openapi_client.models.create_user_settings_dto import \
    CreateUserSettingsDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateUserSettingsDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return CreateUserSettingsDto(
            user_id=str(random.randint(0, 99999)),
            columns=[
                ''
            ],
            dataset_count=1.337,
            job_count=1.337
        )
    else:
        return CreateUserSettingsDto(
            user_id=str(random.randint(0, 99999)),
            columns=[
                ''
            ],
        )


class TestCreateUserSettingsDto(unittest.TestCase):
    """CreateUserSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateUserSettingsDto(self):
        """Test CreateUserSettingsDto"""
        make_instance(include_optional=False)

    def testOptionalCreateUserSettingsDto(self):
        """Test CreateUserSettingsDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
