# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.returned_user_dto import \
    ReturnedUserDto  # noqa: E501


def make_instance(include_optional):
    """Test ReturnedUserDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return ReturnedUserDto(
            id='',
            username='',
            email='',
            email_verified=True,
            realm='',
            auth_strategy=''
        )
    else:
        return ReturnedUserDto(
            id='',
            username='',
            email='',
            auth_strategy='',
        )


class TestReturnedUserDto(unittest.TestCase):
    """ReturnedUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredReturnedUserDto(self):
        """Test ReturnedUserDto"""
        make_instance(include_optional=False)

    def testOptionalReturnedUserDto(self):
        """Test ReturnedUserDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
