# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.create_custom_jwt import \
    CreateCustomJwt  # noqa: E501


def make_instance(include_optional):
    """Test CreateCustomJwt
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return CreateCustomJwt(
            expires_in='10000000'
        )
    else:
        return CreateCustomJwt()


class TestCreateCustomJwt(unittest.TestCase):
    """CreateCustomJwt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateCustomJwt(self):
        """Test CreateCustomJwt"""
        make_instance(include_optional=False)

    def testOptionalCreateCustomJwt(self):
        """Test CreateCustomJwt"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
