# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.create_policy_dto import \
    CreatePolicyDto  # noqa: E501


def make_instance(include_optional):
    """Test CreatePolicyDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return CreatePolicyDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            manager=[
                'admin',
                'ingestor'
            ],
            tape_redundancy='',
            auto_archive=True,
            auto_archive_delay=1.337,
            archive_email_notification=True,
            archive_emails_to_be_notified=[
                ''
            ],
            retrieve_email_notification=True,
            retrieve_emails_to_be_notified=[
                ''
            ],
            embargo_period=1.337
        )
    else:
        return CreatePolicyDto(
            owner_group='ingestor',
            manager=[
                'admin',
                'ingestor'
            ],
            tape_redundancy='',
            auto_archive=True,
            auto_archive_delay=1.337,
            archive_email_notification=True,
            archive_emails_to_be_notified=[
                ''
            ],
            retrieve_email_notification=True,
            retrieve_emails_to_be_notified=[
                ''
            ],
            embargo_period=1.337,
        )


class TestCreatePolicyDto(unittest.TestCase):
    """CreatePolicyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreatePolicyDto(self):
        """Test CreatePolicyDto"""
        make_instance(include_optional=False)

    def testOptionalCreatePolicyDto(self):
        """Test CreatePolicyDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
