# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import datetime
import unittest

from scicat_openapi_client.models.create_job_dto import \
    CreateJobDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateJobDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return CreateJobDto(
            email_job_initiator='pi@email.invalid',
            type='',
            execution_time=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            job_params={},
            job_status_message='',
            dataset_list=[],
            job_result_object={}
        )
    else:
        return CreateJobDto(
            email_job_initiator='pi@email.invalid',
            type='',
            dataset_list=[],
        )


class TestCreateJobDto(unittest.TestCase):
    """CreateJobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateJobDto(self):
        """Test CreateJobDto"""
        make_instance(include_optional=False)

    def testOptionalCreateJobDto(self):
        """Test CreateJobDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
