# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import datetime
import random
import time
import unittest

import scicat_openapi_client
from scicat_openapi_client.models.create_orig_datablock_dto import \
    CreateOrigDatablockDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateOrigDatablockDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return CreateOrigDatablockDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            dataset_id="",
            size=1,
            chk_alg='sha512',
            data_file_list=[
                scicat_openapi_client.models.data_file.DataFile(
                    path='/',
                    size=1.337,
                    time=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    chk='sha512',
                    uid='1000',
                    gid='1000',
                    perm='1', )
            ]
        )
    else:
        return CreateOrigDatablockDto(
            dataset_id="",
            size=1,
            data_file_list=[
                scicat_openapi_client.models.data_file.DataFile(
                    path='/',
                    size=1,
                    time=datetime.datetime.strptime(
                        '2013-10-20 19:20:30.00',
                        '%Y-%m-%d %H:%M:%S.%f'),
                    chk='sha512',
                    uid='1000',
                    gid='1000',
                    perm='1', )
            ],
        )


class TestCreateOrigDatablockDto(unittest.TestCase):
    """CreateOrigDatablockDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateOrigDatablockDto(self):
        """Test CreateOrigDatablockDto"""
        make_instance(include_optional=False)

    def testOptionalCreateOrigDatablockDto(self):
        """Test CreateOrigDatablockDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
