# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

import scicat_openapi_client
from scicat_openapi_client.api.origdatablocks_api import \
    OrigdatablocksApi  # noqa: E501
from test import api_client, login, logout
from test.test_create_orig_datablock_dto import \
    make_instance as make_instance_orig_datablock_create
from test.test_update_orig_datablock_dto import \
    make_instance as make_instance_orig_datablock_update
from test.test_create_raw_dataset_dto import \
    make_instance as make_instance_dataset_create


class TestOrigdatablocksApi(unittest.TestCase):
    """OrigdatablocksApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = (scicat_openapi_client.api.origdatablocks_api
                   .OrigdatablocksApi(api_client))  # noqa: E501
        cls.api_dataset = scicat_openapi_client.api.datasets_api.DatasetsApi(
            api_client)  # noqa: E501
        login(cls.api, 'ingestor')
        login(cls.api_dataset, 'ingestor')

    @classmethod
    def tearDownClass(cls):
        logout(cls.api)
        logout(cls.api_dataset)

    def setUp(self):
        dataset = self.api_dataset.datasets_controller_create(
            make_instance_dataset_create(False))
        datablock = make_instance_orig_datablock_create(False)
        datablock.dataset_id = dataset.pid
        self.datablock = self.api.orig_datablocks_controller_create()

    def test_orig_datablocks_controller_create(self):
        """Test case for orig_datablocks_controller_create

        It creates a new orig datablock for the specified dataset.  # noqa:
        E501
        """
        dataset = self.api_dataset.datasets_controller_create(
            make_instance_dataset_create(False))
        datablock = make_instance_orig_datablock_create(False)
        datablock.dataset_id = dataset.pid
        self.api.orig_datablocks_controller_create()

    def test_orig_datablocks_controller_find_all(self):
        """Test case for orig_datablocks_controller_find_all

        It returns a list of orig datablocks.  # noqa: E501
        """
        self.api.orig_datablocks_controller_find_all()

    def test_orig_datablocks_controller_find_by_id(self):
        """Test case for orig_datablocks_controller_find_by_id

        It retrieve the origdatablock.  # noqa: E501
        """
        self.api.orig_datablocks_controller_find_by_id(self.datablock.id)

    def test_orig_datablocks_controller_fullfacet(self):
        """Test case for orig_datablocks_controller_fullfacet

        """
        self.api.orig_datablocks_controller_fullfacet()

    def test_orig_datablocks_controller_fullfacet_files(self):
        """Test case for orig_datablocks_controller_fullfacet_files

        """
        self.api.orig_datablocks_controller_fullfacet_files()

    def test_orig_datablocks_controller_fullquery(self):
        """Test case for orig_datablocks_controller_fullquery

        """
        self.api.orig_datablocks_controller_fullquery()

    def test_orig_datablocks_controller_fullquery_files(self):
        """Test case for orig_datablocks_controller_fullquery_files

        """
        self.api.orig_datablocks_controller_fullquery_files()

    def test_orig_datablocks_controller_is_valid(self):
        """Test case for orig_datablocks_controller_is_valid

        It validates the orig datablock provided as input.  # noqa: E501
        """
        self.api.orig_datablocks_controller_is_valid(
            make_instance_orig_datablock_create(False))

    def test_orig_datablocks_controller_remove(self):
        """Test case for orig_datablocks_controller_remove

        It deletes the origdatablock.  # noqa: E501
        """
        self.api.orig_datablocks_controller_remove(self.datablock.id)

    def test_orig_datablocks_controller_update(self):
        """Test case for orig_datablocks_controller_update

        It updates the origdatablock.  # noqa: E501
        """
        self.api.orig_datablocks_controller_update(
            self.datablock.id,
            make_instance_orig_datablock_update(False)
        )


if __name__ == '__main__':
    unittest.main()
