# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.user_settings import \
    UserSettings  # noqa: E501


def make_instance(include_optional):
    """Test UserSettings
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return UserSettings(
            columns=[
                ''
            ],
            dataset_count=1.337,
            job_count=1.337,
            user_id=''
        )
    else:
        return UserSettings(
            columns=[
                ''
            ],
            dataset_count=1.337,
            job_count=1.337,
            user_id='',
        )


class TestUserSettings(unittest.TestCase):
    """UserSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredUserSettings(self):
        """Test UserSettings"""
        make_instance(include_optional=False)

    def testOptionalUserSettings(self):
        """Test UserSettings"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
