# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import datetime
import random
import time
import unittest

from scicat_openapi_client.models.attachment import Attachment  # noqa: E501


def make_instance(include_optional):
    """Test Attachment
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return Attachment(
            created_by='ingestor',
            updated_by='ingestor',
            created_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            is_published=True,
            id=str(random.randint(0, 99999)),
            thumbnail='Thumbnail',
            caption='Caption',
            dataset_id=str(random.randint(0, 99999)),
            proposal_id=str(random.randint(0, 99999)),
            sample_id=str(random.randint(0, 99999))
        )
    else:
        return Attachment(
            created_by='ingestor',
            updated_by='ingestor',
            created_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            is_published=True,
            id=str(random.randint(0, 99999)),
            thumbnail='Thumbnail',
            caption='Caption',
        )


class TestAttachment(unittest.TestCase):
    """Attachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredAttachment(self):
        """Test Attachment"""
        make_instance(include_optional=False)

    def testOptionalAttachment(self):
        """Test Attachment"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
