# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.returned_auth_login_dto_user import \
    ReturnedAuthLoginDtoUser  # noqa: E501


def make_instance(include_optional):
    """Test ReturnedAuthLoginDtoUser
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return ReturnedAuthLoginDtoUser(
            id='',
            username='',
            email='',
            email_verified=True,
            realm='',
            auth_strategy=''
        )
    else:
        return ReturnedAuthLoginDtoUser(
            id='',
            username='',
            email='',
            auth_strategy='',
        )


class TestReturnedAuthLoginDtoUser(unittest.TestCase):
    """ReturnedAuthLoginDtoUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredReturnedAuthLoginDtoUser(self):
        """Test ReturnedAuthLoginDtoUser"""
        make_instance(include_optional=False)

    def testOptionalReturnedAuthLoginDtoUser(self):
        """Test ReturnedAuthLoginDtoUser"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
