# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import unittest

from scicat_openapi_client.models.update_attachment_dto import \
    UpdateAttachmentDto  # noqa: E501


def make_instance(include_optional):
    """Test UpdateAttachmentDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return UpdateAttachmentDto(
            owner_group='ingestor',
            access_groups=[
                'admin',
                'ingestor'
            ],
            instrument_group='instrument',
            id=str(random.randint(0, 99999)),
            dataset_id='',
            proposal_id='',
            sample_id='',
            thumbnail='Thumbnail',
            caption='Caption'
        )
    else:
        return UpdateAttachmentDto()


class TestUpdateAttachmentDto(unittest.TestCase):
    """UpdateAttachmentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredUpdateAttachmentDto(self):
        """Test UpdateAttachmentDto"""
        make_instance(include_optional=False)

    def testOptionalUpdateAttachmentDto(self):
        """Test UpdateAttachmentDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
