# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import unittest

from scicat_openapi_client.models.credentials_dto import \
    CredentialsDto  # noqa: E501


def make_instance(include_optional):
    """Test CredentialsDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    if include_optional:
        return CredentialsDto(
            username='ingestor',
            password='aman'
        )
    else:
        return CredentialsDto(
            username='ingestor',
            password='aman',
        )


class TestCredentialsDto(unittest.TestCase):
    """CredentialsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCredentialsDto(self):
        """Test CredentialsDto"""
        make_instance(include_optional=False)

    def testOptionalCredentialsDto(self):
        """Test CredentialsDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
