# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""
import random
import time
import unittest

from scicat_openapi_client.models.create_instrument_dto import \
    CreateInstrumentDto  # noqa: E501


def make_instance(include_optional):
    """Test CreateInstrumentDto
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return CreateInstrumentDto(
            unique_name='instrument_{}'.format(random.randint(0, 99999)),
            name='instrument',
            custom_metadata={}
        )
    else:
        return CreateInstrumentDto(
            unique_name='instrument_{}'.format(random.randint(0, 99999)),
            name='instrument',
        )


class TestCreateInstrumentDto(unittest.TestCase):
    """CreateInstrumentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredCreateInstrumentDto(self):
        """Test CreateInstrumentDto"""
        make_instance(include_optional=False)

    def testOptionalCreateInstrumentDto(self):
        """Test CreateInstrumentDto"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
