# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import datetime
import random
import time
import unittest

from scicat_openapi_client.models.history_class import \
    HistoryClass  # noqa: E501


def make_instance(include_optional):
    """Test HistoryClass
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included """
    random.seed(time.perf_counter())
    if include_optional:
        return HistoryClass(
            id=str(random.randint(0, 99999)),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_by='ingestor'
        )
    else:
        return HistoryClass(
            id=str(random.randint(0, 99999)),
            updated_at=datetime.datetime.strptime(
                '2013-10-20 19:20:30.00',
                '%Y-%m-%d %H:%M:%S.%f'),
            updated_by='ingestor',
        )


class TestHistoryClass(unittest.TestCase):
    """HistoryClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequiredHistoryClass(self):
        """Test HistoryClass"""
        make_instance(include_optional=False)

    def testOptionalHistoryClass(self):
        """Test HistoryClass"""
        make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
