# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend  # noqa: E501

    The version of the OpenAPI document: 4.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import scicat_openapi_client
from scicat_openapi_client.api.logbooks_api import LogbooksApi  # noqa: E501
from scicat_openapi_client.rest import ApiException
from test import api_client, login, logout


class TestLogbooksApi(unittest.TestCase):
    """LogbooksApi unit test stubs"""

    @classmethod
    def setUpClass(cls):
        cls.api = scicat_openapi_client.api.logbooks_api.LogbooksApi(api_client)  # noqa: E501
        login(cls.api, 'ingestor')

    @classmethod
    def tearDownClass(cls):
        logout(cls.api)

    def test_logbooks_controller_find_all(self):
        """Test case for logbooks_controller_find_all

        """
        self.api.logbooks_controller_find_all()

    def test_logbooks_controller_find_by_name(self):
        """Test case for logbooks_controller_find_by_name

        """
        self.api.logbooks_controller_find_by_name('test', '{}')


if __name__ == '__main__':
    unittest.main()
