import request from "supertest";
import { INestApplication, VersioningType } from "@nestjs/common";
import { getConnectionToken } from "@nestjs/mongoose";
import { Connection } from "mongoose";
import { createTestingModuleFactory } from "./utlis";
import { HttpService } from "@nestjs/axios";
import { of } from "rxjs";
import { AxiosResponse } from "@nestjs/terminus/dist/health-indicator/http/axios.interfaces";

describe("Published data datacite test", () => {
  let app: INestApplication;
  let mongoConnection: Connection;
  let token: string;
  let httpService: HttpService;

  let doi: string;

  beforeAll(async () => {
    const moduleFixture = await createTestingModuleFactory().compile();

    app = moduleFixture.createNestApplication();
    app.setGlobalPrefix("api");
    app.enableVersioning({
      type: VersioningType.URI,
      defaultVersion: "3",
    });
    await app.init();
    mongoConnection = await app.get<Promise<Connection>>(getConnectionToken());
    httpService = moduleFixture.get<HttpService>(HttpService);
  });

  beforeAll(async () => {
    await request(app.getHttpServer())
      .post("/api/v3/auth/login")
      .send({
        username: "adminIngestor",
        password: "13f4242dc691a3ee3bb5ca2006edcdf7",
      })
      .set("Accept", "application/json")
      .expect(201)
      .then((response) => (token = response.body.access_token));
  });

  beforeAll(async () => {
    const publishedData = {
      title: "Api test published data",
      abstract: "Published data generated by API test",
      metadata: {
        creators: [{ name: "ESS" }],
        publisher: { name: "ESS", publisherIdentifierScheme: "testScheme" },
        publicationYear: 2020,
        resourceType: "raw",
      },
      datasetPids: [],
    };
    await request(app.getHttpServer())
      .post("/api/v4/PublishedData")
      .send(publishedData)
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${token}` })
      .expect(201)
      .expect("Content-Type", /json/)
      .then((res) => (doi = encodeURIComponent(res.body["doi"])));
  });

  afterAll(async () => {
    if (mongoConnection.db) await mongoConnection.db.dropDatabase();
    await app.close();
  });

  it("Should register this new published data", async () => {
    const mockAxiosResponse: AxiosResponse = {
      data: {},
      status: 200,
      statusText: "OK",
      headers: {},
      config: {},
    };
    jest.spyOn(httpService, "request").mockReturnValue(of(mockAxiosResponse));
    await request(app.getHttpServer())
      .post("/api/v4/PublishedData/" + doi + "/register")
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${token}` })
      .expect(201)
      .expect("Content-Type", /json/);
  });

  it("Should fetch this new published data", async () => {
    await request(app.getHttpServer())
      .get("/api/v4/PublishedData/" + doi)
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${token}` })
      .expect(200)
      .expect("Content-Type", /json/)
      .then((res) => {
        expect(res.body.status).toEqual("registered");
      });
  });

  it("Should not be able to delete published data in registrated", async () => {
    let archiveManagerToken: string;
    await request(app.getHttpServer())
      .post("/api/v3/auth/login")
      .send({
        username: "archiveManager",
        password: "6d3b76392e6f41b087c11f8b77e3f9de",
      })
      .set("Accept", "application/json")
      .expect(201)
      .then((response) => (archiveManagerToken = response.body.access_token));
    await request(app.getHttpServer())
      .delete("/api/v4/PublishedData/" + doi)
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${archiveManagerToken}` })
      .expect(400)
      .expect("Content-Type", /json/);
  });

  it("Should amend this new registered published data", async () => {
    await request(app.getHttpServer())
      .post("/api/v4/PublishedData/" + doi + "/amend")
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${token}` })
      .expect(201)
      .expect("Content-Type", /json/);
  });

  it("Should fetch this amended published data", async () => {
    await request(app.getHttpServer())
      .get("/api/v4/PublishedData/" + doi)
      .set("Accept", "application/json")
      .set({ Authorization: `Bearer ${token}` })
      .expect(200)
      .expect("Content-Type", /json/)
      .then((res) => {
        expect(res.body.status).toEqual("amended");
      });
  });
});
