# gives a docker image below 200 MB
FROM node:9.4

ENV NODE_ENV "qa"
ENV PORT 3000
EXPOSE 3000
# create local user to avoid running as root
RUN addgroup mygroup 
RUN useradd -ms /bin/bash myuser
RUN mkdir -p /usr/src/app && chown -R myuser /usr/src/app
RUN apt update && apt install -y rabbitmq-server
RUN service rabbitmq-server start
# Prepare app directory
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
RUN npm config set -g production false
# USER myuser
# Install our packages
RUN npm install

#  patch for loopback-component-passport
RUN sed -i "s|relations: modelDefinition.relations,|relations: modelDefinition.relations,acls: modelDefinition.acls|" node_modules/loopback-component-passport/lib/index.js

# Copy the rest of our application, node_modules is ignored via .dockerignore
COPY . /usr/src/app
COPY CI/PSI/envfiles/config.local.js /usr/src/app/server/
COPY CI/PSI/envfiles/middleware.json /usr/src/app/server/
COPY CI/PSI/envfiles/providers.json /usr/src/app/server/
COPY CI/PSI/envfiles/datasources.json /usr/src/app/server/
COPY CI/PSI/envfiles/component-config.json /usr/src/app/server/
# Start the app
RUN cat /usr/src/app/server/component-config.json
# RUN curl 127.0.0.1:5672
# CMD ["npm", "run", "test"]
