# gives a docker image below 200 MB
FROM mhart/alpine-node:6

ENV NODE_ENV "production"
ENV PORT 3000
EXPOSE 3000
# create local user to avoid running as root
RUN addgroup mygroup && adduser -D -G mygroup myuser && mkdir -p /usr/src/app && chown -R myuser /usr/src/app

# Prepare app directory
WORKDIR /usr/src/app
COPY envfiles/ /usr/src/app/server
COPY package.json /usr/src/app/

USER myuser
# Install our packages
RUN npm install --production

#  patch for loopback-component-passport
RUN sed -i "s|relations: modelDefinition.relations,|relations: modelDefinition.relations,acls: modelDefinition.acls|" node_modules/loopback-component-passport/lib/index.js

# Copy the rest of our application, node_modules is ignored via .dockerignore
COPY . /usr/src/app

# Start the app
CMD ["npm", "run", "test"]
