export enum Action {
  Manage = "manage",
  Create = "create",
  Read = "read",
  ReadOwn = "readown",
  ReadAll = "readall",
  Update = "update",
  Delete = "delete",
  ListOwn = "listown",
  ListAll = "listall",
  // Users actions
  UserReadOwn = "user_read_own",
  UserReadAny = "user_read_any",
  UserCreateOwn = "user_create_own",
  UserCreateAny = "user_create_any",
  UserUpdateOwn = "user_update_own",
  UserUpdateAny = "user_update_any",
  UserDeleteOwn = "user_delete_own",
  UserDeleteAny = "user_delete_any",
  UserCreateJwt = "user_create_jwt",
  // Instrument actions
  InstrumentRead = "instrument_read",
  InstrumentUpdate = "instrument_update",
  InstrumentCreate = "instrument_create",
  InstrumentDelete = "instrument_delete",
}
