# coding: utf-8

"""
    dacat-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.proposal import Proposal


class TestProposal(unittest.TestCase):
    """ Proposal unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProposal(self):
        """
        Test Proposal
        """
        model = swagger_client.models.proposal.Proposal()


if __name__ == '__main__':
    unittest.main()
