# coding: utf-8

"""
    dacat-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.measurement_period import MeasurementPeriod


class TestMeasurementPeriod(unittest.TestCase):
    """ MeasurementPeriod unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurementPeriod(self):
        """
        Test MeasurementPeriod
        """
        model = swagger_client.models.measurement_period.MeasurementPeriod()


if __name__ == '__main__':
    unittest.main()
