# coding: utf-8

"""
    dacat-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.policy import Policy


class TestPolicy(unittest.TestCase):
    """ Policy unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicy(self):
        """
        Test Policy
        """
        model = swagger_client.models.policy.Policy()


if __name__ == '__main__':
    unittest.main()
