# coding: utf-8

"""
    dacat-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_credential_api import UserCredentialApi


class TestUserCredentialApi(unittest.TestCase):
    """ UserCredentialApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_credential_api.UserCredentialApi()

    def tearDown(self):
        pass

    def test_user_credential_count(self):
        """
        Test case for user_credential_count

        Count instances of the model matched by where from the data source.
        """
        pass

    def test_user_credential_create(self):
        """
        Test case for user_credential_create

        Create a new instance of the model and persist it into the data source.
        """
        pass

    def test_user_credential_create_change_stream_get_user_credentials_change_stream(self):
        """
        Test case for user_credential_create_change_stream_get_user_credentials_change_stream

        Create a change stream.
        """
        pass

    def test_user_credential_create_change_stream_post_user_credentials_change_stream(self):
        """
        Test case for user_credential_create_change_stream_post_user_credentials_change_stream

        Create a change stream.
        """
        pass

    def test_user_credential_delete_by_id(self):
        """
        Test case for user_credential_delete_by_id

        Delete a model instance by {{id}} from the data source.
        """
        pass

    def test_user_credential_exists_get_user_credentialsid_exists(self):
        """
        Test case for user_credential_exists_get_user_credentialsid_exists

        Check whether a model instance exists in the data source.
        """
        pass

    def test_user_credential_exists_head_user_credentialsid(self):
        """
        Test case for user_credential_exists_head_user_credentialsid

        Check whether a model instance exists in the data source.
        """
        pass

    def test_user_credential_find(self):
        """
        Test case for user_credential_find

        Find all instances of the model matched by filter from the data source.
        """
        pass

    def test_user_credential_find_by_id(self):
        """
        Test case for user_credential_find_by_id

        Find a model instance by {{id}} from the data source.
        """
        pass

    def test_user_credential_find_one(self):
        """
        Test case for user_credential_find_one

        Find first instance of the model matched by filter from the data source.
        """
        pass

    def test_user_credential_patch_or_create(self):
        """
        Test case for user_credential_patch_or_create

        Patch an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_credential_prototype_get_user(self):
        """
        Test case for user_credential_prototype_get_user

        Fetches belongsTo relation user.
        """
        pass

    def test_user_credential_prototype_patch_attributes(self):
        """
        Test case for user_credential_prototype_patch_attributes

        Patch attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_credential_replace_by_id_post_user_credentialsid_replace(self):
        """
        Test case for user_credential_replace_by_id_post_user_credentialsid_replace

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_credential_replace_by_id_put_user_credentialsid(self):
        """
        Test case for user_credential_replace_by_id_put_user_credentialsid

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_credential_replace_or_create_post_user_credentials_replace_or_create(self):
        """
        Test case for user_credential_replace_or_create_post_user_credentials_replace_or_create

        Replace an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_credential_replace_or_create_put_user_credentials(self):
        """
        Test case for user_credential_replace_or_create_put_user_credentials

        Replace an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_credential_update_all(self):
        """
        Test case for user_credential_update_all

        Update instances of the model matched by {{where}} from the data source.
        """
        pass

    def test_user_credential_upsert_with_where(self):
        """
        Test case for user_credential_upsert_with_where

        Update an existing model instance or insert a new one into the data source based on the where criteria.
        """
        pass


if __name__ == '__main__':
    unittest.main()
