# coding: utf-8

"""
    dacat-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """ UserApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_api.UserApi()

    def tearDown(self):
        pass

    def test_user_change_password(self):
        """
        Test case for user_change_password

        Change a user's password.
        """
        pass

    def test_user_confirm(self):
        """
        Test case for user_confirm

        Confirm a user registration with email verification token.
        """
        pass

    def test_user_count(self):
        """
        Test case for user_count

        Count instances of the model matched by where from the data source.
        """
        pass

    def test_user_create(self):
        """
        Test case for user_create

        Create a new instance of the model and persist it into the data source.
        """
        pass

    def test_user_create_change_stream_get_users_change_stream(self):
        """
        Test case for user_create_change_stream_get_users_change_stream

        Create a change stream.
        """
        pass

    def test_user_create_change_stream_post_users_change_stream(self):
        """
        Test case for user_create_change_stream_post_users_change_stream

        Create a change stream.
        """
        pass

    def test_user_delete_by_id(self):
        """
        Test case for user_delete_by_id

        Delete a model instance by {{id}} from the data source.
        """
        pass

    def test_user_exists_get_usersid_exists(self):
        """
        Test case for user_exists_get_usersid_exists

        Check whether a model instance exists in the data source.
        """
        pass

    def test_user_exists_head_usersid(self):
        """
        Test case for user_exists_head_usersid

        Check whether a model instance exists in the data source.
        """
        pass

    def test_user_find(self):
        """
        Test case for user_find

        Find all instances of the model matched by filter from the data source.
        """
        pass

    def test_user_find_by_id(self):
        """
        Test case for user_find_by_id

        Find a model instance by {{id}} from the data source.
        """
        pass

    def test_user_find_one(self):
        """
        Test case for user_find_one

        Find first instance of the model matched by filter from the data source.
        """
        pass

    def test_user_login(self):
        """
        Test case for user_login

        Login a user with username/email and password.
        """
        pass

    def test_user_logout(self):
        """
        Test case for user_logout

        Logout a user with access token.
        """
        pass

    def test_user_patch_or_create(self):
        """
        Test case for user_patch_or_create

        Patch an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_prototype_count_access_tokens(self):
        """
        Test case for user_prototype_count_access_tokens

        Counts accessTokens of User.
        """
        pass

    def test_user_prototype_create_access_tokens(self):
        """
        Test case for user_prototype_create_access_tokens

        Creates a new instance in accessTokens of this model.
        """
        pass

    def test_user_prototype_delete_access_tokens(self):
        """
        Test case for user_prototype_delete_access_tokens

        Deletes all accessTokens of this model.
        """
        pass

    def test_user_prototype_destroy_by_id_access_tokens(self):
        """
        Test case for user_prototype_destroy_by_id_access_tokens

        Delete a related item by id for accessTokens.
        """
        pass

    def test_user_prototype_find_by_id_access_tokens(self):
        """
        Test case for user_prototype_find_by_id_access_tokens

        Find a related item by id for accessTokens.
        """
        pass

    def test_user_prototype_get_access_tokens(self):
        """
        Test case for user_prototype_get_access_tokens

        Queries accessTokens of User.
        """
        pass

    def test_user_prototype_patch_attributes(self):
        """
        Test case for user_prototype_patch_attributes

        Patch attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_prototype_update_by_id_access_tokens(self):
        """
        Test case for user_prototype_update_by_id_access_tokens

        Update a related item by id for accessTokens.
        """
        pass

    def test_user_replace_by_id_post_usersid_replace(self):
        """
        Test case for user_replace_by_id_post_usersid_replace

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_replace_by_id_put_usersid(self):
        """
        Test case for user_replace_by_id_put_usersid

        Replace attributes for a model instance and persist it into the data source.
        """
        pass

    def test_user_replace_or_create_post_users_replace_or_create(self):
        """
        Test case for user_replace_or_create_post_users_replace_or_create

        Replace an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_replace_or_create_put_users(self):
        """
        Test case for user_replace_or_create_put_users

        Replace an existing model instance or insert a new one into the data source.
        """
        pass

    def test_user_reset_password(self):
        """
        Test case for user_reset_password

        Reset password for a user with email.
        """
        pass

    def test_user_update_all(self):
        """
        Test case for user_update_all

        Update instances of the model matched by {{where}} from the data source.
        """
        pass

    def test_user_upsert_with_where(self):
        """
        Test case for user_upsert_with_where

        Update an existing model instance or insert a new one into the data source based on the where criteria.
        """
        pass


if __name__ == '__main__':
    unittest.main()
