FROM node:18-alpine

RUN apk update && apk upgrade && \
  apk add --no-cache git

ENV PORT 3000
EXPOSE 3000

# Prepare app directory
WORKDIR /home/node/app
COPY package*.json /home/node/app/

# set up local user to avoid running as root
RUN chown -R node:node /home/node/app
USER node

# Install our packages
RUN npm ci --omit=optional

# Copy the rest of our application, node_modules is ignored via .dockerignore
COPY --chown=node:node . /home/node/app
COPY --chown=node:node CI/ESS/wait.sh /home/node/app/

# Start the app
CMD ["./wait.sh"]
