# gives a docker image below 200 MB
FROM node:9

ENV PORT 3000
EXPOSE 3000
# create local user to avoid running as root

# Prepare app directory
WORKDIR /usr/src/app
COPY package.json /usr/src/app/
# Install our packages
RUN npm install

#  patch for loopback-component-passport
RUN sed -i "s|relations: modelDefinition.relations,|relations: modelDefinition.relations,acls: modelDefinition.acls|" node_modules/loopback-component-passport/lib/index.js

# Copy the rest of our application, node_modules is ignored via .dockerignore
COPY . /usr/src/app
COPY CI/ESS/envfiles/config.ess.js /usr/src/app/server/config.local.js
COPY CI/ESS/envfiles/middleware.json /usr/src/app/server/
COPY CI/ESS/envfiles/providers.json /usr/src/app/server/
COPY CI/ESS/envfiles/datasources.json /usr/src/app/server/
COPY CI/ESS/envfiles/component-config.json /usr/src/app/server/
# Start the app
CMD ["npm", "run", "test"]
