version: "3"
services:
    mongodb:
        image: mongo:latest
    scicat-backend:
        build:
            context: .
            dockerfile: CI/ESS/Dockerfile.test
        depends_on:
            - mongodb
