node('docker') {
  stage('Checkout'){
    checkout scm
  }
  stage('Build Docker'){
    withCredentials([ usernamePassword(credentialsId: 'dockerhubess',usernameVariable: 'docker_user',passwordVariable: 'docker_password' )]) {
      sh 'docker login -u essdmscdm -p $docker_password '
      def IMAGE_ID = sh ( script: 'git rev-parse HEAD',returnStdout: true).trim()
      sh "docker build --file CI/ESS/Dockerfile.proxy . --tag dacat/catamel:latest -t dacat/catamel:${IMAGE_ID}dev" 
      echo "Git image id : ${IMAGE_ID}"
      sh "docker push dacat/catamel:${IMAGE_ID}dev"
      sh "docker push dacat/catamel:latest"
    }
  }
  stage('SuperTest Catamel ') {
    //sh 'docker run  --privileged -t catamel_test npm run test'
  }
}

