node ('docker') {
       stage('Checkout'){

          checkout scm
       }


       stage('Build Docker') {
            sh 'docker  build -f CI/ESS/Dockerfile.proxy  .'
       }
       stage('SuperTest Catamel ') {
            sh 'docker run  --privileged -t catamel_test npm run test'
       }

}
