export enum ScientificRelation {
  EQUAL_TO_STRING = "EQUAL_TO_STRING",
  EQUAL_TO_NUMERIC = "EQUAL_TO_NUMERIC",
  GREATER_THAN = "GREATER_THAN",
  LESS_THAN = "LESS_THAN",
  CONTAINS_STRING = "CONTAINS_STRING",
  GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL",
  LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL",
  RANGE = "RANGE",
}
